# Generated by Django 5.1.2 on 2024-10-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_capsule_timeline_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='noticed_at',
            field=models.DateTimeField(),
        ),
    ]
