# Generated by Django 5.1.2 on 2024-10-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_timeline_noticed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='open_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='open_requested_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='opened_member',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
