# Generated by Django 5.1.2 on 2024-10-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_capsule_open_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='open_requested_at',
            field=models.DateTimeField(),
        ),
    ]
